[config]
mode = "conv"
target_length = 48000
nfft = 1024
hop_length = 512
nmels = 40
batch_size = 32
divide_4 = true 
[parameters]
epochs = 15
number_of_conv_layers = 4
filter_start = 8
step_size = 16
max_pooling = false 